"""Exact d4 falsification audit for the proposed Laguerre source identity.

The computation stays in the characteristic-zero moment algebra generated by
the already imposed Q-moment equations.  It deliberately does not claim that
every formal moment point is an actual probability law; the conclusion is
that the proposed identity is not a consequence of the currently available
Fock/Q-law relations unless an additional relation forces c2 = 0.
"""
from __future__ import annotations

import json
from pathlib import Path

import sympy as sp


def iid_expect(expr: sp.Expr, moments: dict[int, sp.Expr]) -> sp.Expr:
    x1, x2, x3 = sp.symbols("x1 x2 x3")
    poly = sp.Poly(sp.expand(expr), x1, x2, x3)
    out = sp.Integer(0)
    for powers, coeff in poly.terms():
        term = coeff
        for power in powers:
            term *= moments[power]
        out += term
    return sp.expand(out)


def moment_symbols(max_order: int = 11) -> dict[int, sp.Expr]:
    return {
        0: sp.Integer(1),
        1: sp.Integer(0),
        2: sp.Integer(1),
        **{k: sp.Symbol(f"mu{k}", real=True) for k in range(3, max_order + 1)},
    }


def build_target_quotient() -> tuple[dict[int, sp.Expr], dict[sp.Symbol, sp.Expr]]:
    x1, x2, x3 = sp.symbols("x1 x2 x3")
    q = sp.expand(x1**2 + x2**2 + x3**2 - (x1 + x2 + x3) ** 2 / 3)
    moments = moment_symbols(11)
    q_moments = [iid_expect(q**k, moments) for k in range(1, 6)]
    substitutions: dict[sp.Symbol, sp.Expr] = {}
    targets = {2: 8, 3: 48, 4: 384, 5: 3840}
    for power, target in targets.items():
        equation = sp.expand(q_moments[power - 1].subs(substitutions) - target)
        unknown = sp.Symbol(f"mu{2 * power}", real=True)
        solutions = sp.solve(equation, unknown, dict=True)
        if len(solutions) != 1:
            raise AssertionError(f"could not eliminate {unknown}: {solutions}")
        substitutions.update(solutions[0])
    return moments, substitutions


def compute_exact_audit() -> dict[str, object]:
    x1, x2, x3 = sp.symbols("x1 x2 x3")
    bar = (x1 + x2 + x3) / 3
    q = sp.expand(x1**2 + x2**2 + x3**2 - (x1 + x2 + x3) ** 2 / 3)
    moments, substitutions = build_target_quotient()

    c = {
        n: sp.factor(iid_expect(bar * sp.laguerre(n, q / 2), moments).subs(substitutions))
        for n in range(1, 4)
    }
    d = {
        n: sp.factor(iid_expect(bar**2 * sp.laguerre(n, q / 2), moments).subs(substitutions))
        for n in range(5)
    }

    predicted = sp.expand(5 * c[1] * c[3] + sp.Rational(5, 2) * c[2] ** 2)
    difference = sp.factor(d[4] - predicted)
    c2_square_difference = sp.factor(difference - sp.Rational(2, 3) * c[2] ** 2)

    low_order_checks = {
        "d0": sp.simplify(d[0] - sp.Rational(1, 3)) == 0,
        "d1": sp.simplify(d[1]) == 0,
        "d2": sp.simplify(d[2] - sp.Rational(3, 2) * c[1] ** 2) == 0,
        "d3": sp.simplify(d[3] - 4 * c[1] * c[2]) == 0,
    }
    return {
        "target_eliminations": {str(k): str(v) for k, v in substitutions.items()},
        "c1_c3": {str(k): str(v) for k, v in c.items()},
        "d0_d4": {str(k): str(v) for k, v in d.items()},
        "star_predicted_d4": str(sp.factor(predicted)),
        "d4_minus_star": str(difference),
        "d4_minus_star_over_c2_square": str(sp.factor(difference / c[2] ** 2)),
        "corrected_d4_residual": str(c2_square_difference),
        "low_order_checks": low_order_checks,
        "star_formally_refuted": difference != 0,
        "interpretation": (
            "The proposed identity fails in the known characteristic-zero "
            "Q-moment quotient by (2/3)c2^2. This is not an actual probability "
            "counterexample; an additional all-orders realizability identity "
            "would be needed to force c2=0 before the identity could hold."
        ),
    }


def main() -> None:
    result = compute_exact_audit()
    out = Path(__file__).resolve().parent / "results" / "r19_audit.json"
    out.parent.mkdir(exist_ok=True)
    out.write_text(json.dumps(result, indent=2), encoding="utf-8")
    for name, ok in result["low_order_checks"].items():
        print(f"R19_{name.upper()}_CHECK {'PASSED' if ok else 'FAILED'}")
    print(f"R19_D4_MINUS_STAR {result['d4_minus_star']}")
    print(f"R19_D4_MINUS_STAR_OVER_C2_SQUARE {result['d4_minus_star_over_c2_square']}")
    print(
        "R19_PROPOSED_SOURCE_HESSIAN_IDENTITY "
        + ("REFUTED_IN_KNOWN_Q_MOMENT_QUOTIENT" if result["star_formally_refuted"] else "NOT_REFUTED")
    )
    print("R19_ADDITIONAL_ALL_ORDERS_CONSTRAINT_REQUIRED")
    print("R19_AUDIT_COMPLETED")


if __name__ == "__main__":
    main()
